export enum USER_ROLE {
  ADMIN_ROLE = 'ADMIN_ROLE',
  MERCHANT_ROLE = 'MERCHANT_ROLE',
  SHADOW_MERCHANT_ROLE = 'SHADOW_MERCHANT_ROLE',
  OPERATOR_ROLE = 'OPERATOR_ROLE',
  TRADER_ROLE = 'TRADER_ROLE',
  DEMO_ROLE = 'DEMO_ROLE',
}

export enum USER_STATUS {
  ACTIVE = 'ACTIVE',
  BLOCKED = 'BLOCKED',
}

export const userAccessRoles: Record<USER_ROLE, USER_ROLE[]> = {
  [USER_ROLE.ADMIN_ROLE]: [USER_ROLE.ADMIN_ROLE],
  [USER_ROLE.OPERATOR_ROLE]: [USER_ROLE.ADMIN_ROLE],
  [USER_ROLE.MERCHANT_ROLE]: [USER_ROLE.ADMIN_ROLE, USER_ROLE.OPERATOR_ROLE],
  [USER_ROLE.SHADOW_MERCHANT_ROLE]: [USER_ROLE.ADMIN_ROLE, USER_ROLE.OPERATOR_ROLE],
  [USER_ROLE.TRADER_ROLE]: [USER_ROLE.ADMIN_ROLE, USER_ROLE.OPERATOR_ROLE],
  [USER_ROLE.DEMO_ROLE]: [USER_ROLE.ADMIN_ROLE, USER_ROLE.OPERATOR_ROLE],
}
